config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  get '/contact' => 'projects#contact', :as => 'contact'
  get '/about' => 'projects#about', :as => 'about'
  root 'projects#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :projects
end

app/models/fabrication.rb
class Fabrication < ActiveRecord::Base
  has_many :projects
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :fabrication

  mount_uploader :avatar, AvatarUploader

  def self.search(search)
    where("title LIKE ?", "%#{search}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_project, only: [:show, :edit, :update, :destroy]

  def index
    #@projects = Project.all.order('created_at DESC')
    if params[:search]
      @projects = Project.search(params[:search]).order("created_at DESC")
    elsif params[:category].blank? && params[:fabrication].blank?
      @projects = Project.all.order('created_at DESC')
    elsif params[:fabrication].blank?
      @category_id = Category.find_by(name: params[:category]).id
      @projects = Project.where(:category_id => @category_id).order('created_at DESC')
    elsif params[:category].blank?
      @fabrication_id = Fabrication.find_by(name: params[:fabrication]).id
      @projects = Project.where(:fabrication_id => @fabrication_id).order('created_at DESC')
    else
      @category_id = Category.find_by(name: params[:category]).id
      @fabrication_id = Fabrication.find_by(name: params[:fabrication]).id
      @projects = Project.where(:fabrication_id => @fabrication_id, :category_id => @category_id).order('created_at DESC')
    end
  end

  def show
  end

  def new
    @project = current_user.projects.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
    @fabrications = Fabrication.all.map{ |f| [f.name, f.id] }
  end

  def create
    @project = current_user.projects.build(project_params)
    @project.category_id = params[:category_id]
    @project.fabrication_id = params[:fabrication_id]

    if @project.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
    @fabrications = Fabrication.all.map{ |f| [f.name, f.id] }
  end

  def update
    @project.category_id = params[:category_id]
    @project.fabrication_id = params[:fabrication_id]
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to root_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :direction, :description, :category_id, :fabrication_id, :avatar)
  end

  def find_project
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_nav.html.erb
<div class="box"><img src="/psicon.png" height="50px" width="110px"></div>
<div class="page-header">
  <ul class="nav navbar-nav super">
    <% if user_signed_in? %>
      <li class="navmenu1"><%= link_to "+ Add New Project", new_project_path %></li>
      <li class="navmenu2"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
        <li class="navmenu1"><%= link_to "Sign Up", new_user_registration_path %></li>
        <li class="navmenu2"><%= link_to "Log In", new_user_session_path %></li>
    <% end %>
  </ul>
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
</div>
<nav class="navbar navbar-default" id="bs-example-navbar-collapse-1">

  <div class="container">

    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <ul class="nav navbar-nav secondary-nav">
      <li role="presentation" class="first-pres"><%= link_to 'INICI', root_path %></li>
      <li role="presentation"><a href="#">GUIA</a></li>
      <li role="presentation"><a href="#">PROJECTES</a></li>
      <li role="presentation"><a href="#">UBICACIONS</a></li>
      <li role="presentation"><%= link_to 'ABOUT', about_path %></li>
      <li role="presentation"><%= link_to 'CONTACTE', contact_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParasiteOS</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Diplomata+SC" rel="stylesheet">
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>
</head>
<body>

<%= render '/layouts/nav' %>

<div class="container-fluid contain-all">
  <%= yield %>
</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for @project, :html => { :multipart => true } do |f| %>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Selecciona categoria") %>    &nbsp;
    <%= select_tag(:fabrication_id, options_for_select(@fabrications), :prompt => "Selecciona tipus de fabricació") %>
    <br/><br/>
    <%= f.file_field :avatar %>
    <br/><br/>
    <%= f.input :title, label: "Títol" %>
    <%= f.input :direction, placeholder: 'Nom carrer,  Núm. carrer,  Codi postal,  Ciutat,  Pais', label: "Direcció" %>
    <%= f.input :description, label: "Descripció" %>
    <%= f.button :submit %>
<% end %>

app/views/projects/about.html.erb
<div id="row-5" class="row row-5">
  <div class="col-md-3"></div>
  <div class="col-md-5 colum-about">
    <p>Aquesta web ha estat fundada com a eina de difusió, com una plataforma per a compartir i posar en contacte a gent i entitats d’arreu del món amb el projecte Paràsit. Aquesta iniciativa  es basa en el disseny personalitzat d’un espai i la seva instal·lació en un entorn desaprofitat.</p>
    <br/>
    <p>El projecte va nàixer de la idea del reaprofitament dels espais en desús, tant públics com privats, i mitjançant la col·locació d’una d’aquestes estructures paràsit, es dota l’espai amb unes noves característiques basades en les necessitats de l’usuari.
    En aquesta web podeu trobar-hi tot el necessari per a realitzar la implantació d’una estructura paràsit, des de la guia amb els passos a seguir per a analitzar l’entorn i els usuaris que l’utilitzaran, fins als plànols i les instruccions per a fabricar i construir l’objecte final.</p>
    <br/>
    <p>La fundadora del projecte Paràsit, va idear el projecte enfocat a les comunitats de veïns i en especial en els membres més veterans d’aquestes comunitats. L’objectiu inicial del projecte era ajudar als sèniors en el seu dia a dia, i així millorar la seva qualitat de vida, però a mesura que va anar avançant el projecte ens vam adonar que tenia moltes més aplicacions i per a molts més usuaris. I així és com va sorgir la guia d’extrapolació per tal d’analitzar cada una de les comunitats i determinar que és el que necessita.</p>
  </div>
  <div class="col-md-4"></div>
</div>

app/views/projects/contact.html.erb
<div id="row-6" class="row row-6">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <form class="form-horizontal">
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <h1 id="rgst-title"><b>Formulari</b></h1>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">Nom</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" placeholder="Nom d'usuari" aria-describedby="basic-addon1">
        </div>
      </div>
      <div class="form-group">
        <label for="exampleInputAmount" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
          <input type="email" class="form-control" id="exampleInputAmount" aria-describedby="inputSuccess2Status" placeholder="Email">
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <div class="checkbox">
            <label>
              <input id="check-terms" type="checkbox"> He llegit i accepto els termes legals.
            </label>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <textarea class="form-control" placeholder="Escriu aquí la teva consulta..." rows="6"></textarea>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-success active btn-green">Enviar</button>
        </div>
      </div>
    </form>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/projects/edit.html.erb
<h1>Editar Projecte</h1>

<%= simple_form_for @project, :html => { :multipart => true } do |f| %>
    <%= f.select :category_id, @categories %>    &nbsp;
    <%= f.select :fabrication_id, @fabrications %>
    <br/><br/>
    <%= f.file_field :avatar %>
    <br/><br/>
    <%= f.input :title, label: "Títol" %>
    <%= f.input :direction, label: "Direcció" %>
    <%= f.input :description, label: "Descripció" %>
    <%= f.button :submit %>
<% end %>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-lg-7">
    <div class="form-group form-inline">

      <label for="catg">Selecciona una categoria:&emsp;</label>
      <div class="dropdown dcat" id="catg">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.name %>">
                <%= link_to category.name, projects_path(category: category.name), class: "link" %>
              </li>
          <% end %>
        </ul>
      </div>

      <label id="fabr-labl" for="fabr">Selecciona tipus de fabricació:&emsp;</label>
      <div class="dropdown dcat" id="fabr">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Fabricació <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <% Fabrication.all.each do |fabrication| %>
              <li class="<%= 'active' if params[:fabrication] == fabrication.name %>">
                <%= link_to fabrication.name, projects_path(fabrication: fabrication.name), class: "link" %>
              </li>
          <% end %>
        </ul>
      </div>

    </div>
  </div><!-- /.col-lg-7 -->
  <div class="col-lg-3" style="margin-top: -4px;">
    <%= form_tag(projects_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Buscar projecte", class: 'form-control' %>
  </div>
  <div class="col-lg-2" style="margin-top: -4px;">
        <%= submit_tag "Search", :name => nil, class: 'btn btn-default' %>
    <% end %>
  </div><!-- /.col-lg-2 -->
</div><!-- /.row -->

<nav class="navbar navbar-default search-nav">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-7">
        <div class="form-group form-inline">

          <label class="sec-fabr-labl" for="catg">Selecciona una categoria:&emsp;</label>
          <div class="dropdown dcat sec-dcat" id="catg">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% Category.all.each do |category| %>
                  <li class="<%= 'active' if params[:category] == category.name %>">
                    <%= link_to category.name, projects_path(category: category.name), class: "link" %>
                  </li>
              <% end %>
            </ul>
          </div>

          <label class="sec-fabr-labl" id="fabr-labl" for="fabr">Selecciona tipus de fabricació:&emsp;</label>
          <div class="dropdown dcat sec-dcat" id="fabr">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Fabricació <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% Fabrication.all.each do |fabrication| %>
                  <li class="<%= 'active' if params[:fabrication] == fabrication.name %>">
                    <%= link_to fabrication.name, projects_path(fabrication: fabrication.name), class: "link" %>
                  </li>
              <% end %>
            </ul>
          </div>

        </div>
      </div><!-- /.col-lg-7 -->
      <div class="col-lg-4" style="margin-top: 12px;">
        <%= form_tag(projects_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Buscar projecte", class: 'form-control' %>
            </div>
            <div class="col-lg-1" style="margin-top: 12px;">
              <%= submit_tag "Search", :name => nil, class: 'btn btn-default' %>
        <% end %>
        </div><!-- /.col-lg-2 -->
        </div><!-- /.row -->
  </div>
</nav>

<% if @projects.count == 0 %>

    <h1>No hi ha cap projecte registrat encara...</h1>

<% else %>

    <div class="row">
        <h1 class="current-category" style="margin: 20px;"><%= params[:category] %></h1>

        <% @projects.each do |project| %>

            <div class="col-md-4">
              <div class="thumbnail" style="min-height: 551px;">
                <img style="max-height: 295px;" width="468" src="<%=
                  if project.avatar?
                    project.avatar_url.to_s
                  else
                    'http://www.cadagency.co.uk/wp-content/uploads/2016/02/fig-2-2.jpg'
                  end %>" alt="...">
                <div class="caption">
                  <h3><%= link_to project.title, project_path(project), class: "projlist" %></h3>
                  <p class="giveMeEllipsis"><%= project.description %></p>
                  <p><a href="#"><%= link_to "Detalls", project_path(project), class: "projlist" %></a>

                    <% if user_signed_in? %>

                        <% if project.user_id == current_user.id %>

                          | <a href="#"><%= link_to "Editar", edit_project_path(project) %></a>
                          | <a href="#"><%= link_to "Eliminar", project_path(project), method: :delete, data: { confirm: "Estàs segur?" } %></a>

                        <% end %>

                    <% end %>

                  </p>
                </div>
              </div>
            </div>

        <% end %>

    </div>

<% end %>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <h1>Nou Projecte</h1>
    <br/><br/>
    <%= render 'form' %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/projects/show.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <h2 style="margin-bottom: 20px;"><%= @project.title %></h2>
    <h4>Adreça: <%= @project.direction %></h4>
    <h5>Categoria: <%=
      if !@project.category.blank?
        @project.category.name
      else
        '-sense especificar-'
      end %></h5>
    <h5>Fabricació: <%=
      if !@project.fabrication.blank?
        @project.fabrication.name
      else
        '-sense especificar-'
      end %></h5>
    <div class="img-cont" style="margin-bottom: 40px;"><img height="500" width="932" src="<%=
      if @project.avatar?
        @project.avatar_url.to_s
      else
        'http://www.cadagency.co.uk/wp-content/uploads/2016/02/fig-2-2.jpg'
      end %>"></div>
    <p class="proj-descript"><%= simple_format @project.description %></p>

    <div id="row-0" class="row row-0">

      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
          <li data-target="#myCarousel" data-slide-to="3"></li>
          <li data-target="#myCarousel" data-slide-to="4"></li>
          <li data-target="#myCarousel" data-slide-to="5"></li>
          <li data-target="#myCarousel" data-slide-to="6"></li>
          <li data-target="#myCarousel" data-slide-to="7"></li>
          <li data-target="#myCarousel" data-slide-to="8"></li>
          <li data-target="#myCarousel" data-slide-to="9"></li>
          <li data-target="#myCarousel" data-slide-to="10"></li>
          <li data-target="#myCarousel" data-slide-to="11"></li>
          <li data-target="#myCarousel" data-slide-to="12"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">

          <div class="item active">
            <img src="/projecte01.jpg" alt="Chania">
          </div>

          <div class="item">
            <img src="/projecte02.jpg" alt="Chicago">
          </div>

          <div class="item">
            <img src="/projecte03.jpg" alt="New York">
          </div>

          <div class="item">
            <img src="/projecte04.jpg" alt="New York">
          </div>

          <div class="item">
            <img src="/projecte05.jpg" alt="New York">
          </div>

          <div class="item">
            <img src="/projecte06.jpg" alt="New York">
          </div>

          <div class="item">
            <img src="/projecte07.jpg" alt="New York">
          </div>

          <div class="item">
            <img src="/projecte08.jpg" alt="New York">
          </div>

          <div class="item">
            <img src="/projecte09.jpg" alt="New York">
          </div>

          <div class="item">
            <img src="/projecte10.jpg" alt="New York">
          </div>

          <div class="item">
            <img src="/projecte11.jpg" alt="New York">
          </div>

          <div class="item">
            <img src="/projecte12.jpg" alt="New York">
          </div>

          <div class="item">
            <img src="/projecte13.jpg" alt="New York">
          </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

    </div>

    <div id="map"></div>

    <%= link_to "Atrás", root_path %>

    <% if user_signed_in? %>

        <% if @project.user_id == current_user.id %>
            <%= "|" %>
            <%= link_to "Editar", edit_project_path(@project) %>
            <%= "|" %>
            <%= link_to "Eliminar", project_path(@project), method: :delete, data: { confirm: "Estàs segur?" } %>
        <% end %>

    <% end %>

  </div>
  <div class="col-md-2"></div>
</div>